### ISSUE TITLE
Where is "open class GateKeeper(.." called?

### ISSUE THREAD

**Issue by a-t-0** [jecsan/gatekeeper#1]
Dear jecsan,

Thank you very much for your work! While trying to modify it to delete a selective list of accounts that are already present in the AccountManager, I was trying to understand where the "[open class GateKeeper(private val accountManager: AccountManager,
                      private val accountType: String) {}](https://github.com/jecsan/gatekeeper/blob/e84c48638a2f86d50d47030563948714c9b9f673/gatekeeper/src/main/java/com/greyblocks/gatekeeper/GateKeeper.kt)" is called.

0. Could you perhaps point me to that location, if it is indeed called from somewhere else?
1. Are the AccountManager and accountType passed into that class from another location? 
2. Or is that the way those variables/objects are defined?

Kind regards.

**Comment by jecsan** [comment]
Hi, sorry for the late reply.

1. The sample project _gatekeepersample_ instantiates the GateKeeper using the said parameters.
2. The reason you need to specify the account_type using xml values is because it is needed by the authenticator.xml.

**Comment by a-t-0** [comment]
Thank you for your elaboration jecsan.
